apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config 
  namespace: n8n 
data:
  N8N_PORT: "5678"

  WEBHOOK_URL: "n8n.sirius-sec.com"
  N8N_LISTEN_ADDRESS: "0.0.0.0"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_SECURE_COOKIE: "true"
  N8N_METRICS: "true"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "35.188.139.22"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8ndb"
  DB_POSTGRESDB_USER: "sirius"
  

