apiVersion: v1
kind: ConfigMap
metadata:
  name: customer1-n8n-config 
  namespace: customer1 
data:
  N8N_PORT: "5678"

  WEBHOOK_URL: "n8n.sirius-sec.com"
  N8N_LISTEN_ADDRESS: "0.0.0.0"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_SECURE_COOKIE: "true"
  N8N_METRICS: "true"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "customer1-db-rw-customer1.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "app" 
  DB_POSTGRESDB_USER: "sirius"
  

