apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer1
resources:
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - storage.yaml
  - http-route.yaml
  - customer1-n8n-secret.yaml 
  - pg-cluster-customer1.yaml
  - customer1-db-secret.yaml

