apiVersion: v1
kind: Service
metadata:
  name: n8n-service  
  namespace: customer1 
  annotations:
    cloud.google.com: '{"ingress": true}'
spec:
  selector:
    app: customer1-n8n 
  ports:
    - port: 80    
      targetPort: 5678
      name: http

