
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer1
resources:
  - analyst-gemini-cronjob.yaml
  - configmap.yaml
  - gemini-apikey.yaml 
  - news-user-db-secret.yaml
  - scraper-cronjob.yaml
  - scrapy-urls-configmap.yaml
  - scrapy-configmap.yaml
  - telebot-cronjob.yaml
  - telebot-secret.yaml 
  
